// src/components/scroll/JoinSides.vue
<script setup lang="ts">
import { motion, useTransform } from "motion-v";
import { computed, ref } from "vue";
import { useEntranceProgress } from "@/composables/useEntranceProgress";

/**
 * Two halves (the `left` and `right` slots) slide in from opposite edges and
 * lock together, with a slight overshoot in rotation as they meet.
 */
const { inline } = defineProps<{
  /** Render spans instead of divs, for use inside headings and other phrasing content. */
  inline?: boolean;
}>();

const anchor = ref<HTMLElement | null>(null);
const { progress, reduced } = useEntranceProgress(anchor, 0.4);

function side(sign: 1 | -1) {
  return {
    x: useTransform(progress, [0, 1], [`${String(sign * 60)}vw`, "0vw"]),
    rotate: useTransform(progress, [0, 0.8, 1], [sign * 8, sign * -1.5, 0]),
    opacity: useTransform(progress, [0, 0.5], [0, 1]),
  };
}
const leftMotion = side(-1);
const rightMotion = side(1);

const leftStyle = computed(() => (reduced.value ? {} : leftMotion));
const rightStyle = computed(() => (reduced.value ? {} : rightMotion));
const tag = computed(() => (inline ? motion.span : motion.div));
const halfClass = computed(() => (inline ? "inline-block" : "min-w-0"));
</script>

<template>
  <component :is="inline ? 'span' : 'div'" ref="anchor" class="overflow-x-clip">
    <component :is="tag" :style="leftStyle" :class="halfClass"><slot name="left" /></component>
    <component :is="tag" :style="rightStyle" :class="halfClass"><slot name="right" /></component>
  </component>
</template>

// src/components/scroll/JoinSides.tsx
import { motion, useTransform, type MotionValue } from "motion/react";
import { useRef, type ReactNode } from "react";
import { cn } from "@/lib/cn";
import { useEntranceProgress } from "./useEntranceProgress";

interface JoinSidesProps {
  left: ReactNode;
  right: ReactNode;
  className?: string;
  /** Render spans instead of divs, for use inside headings and other phrasing content. */
  inline?: boolean;
}

function Half({
  progress,
  from,
  inline,
  children,
}: {
  progress: MotionValue<number>;
  from: "left" | "right";
  inline: boolean;
  children: ReactNode;
}) {
  const sign = from === "left" ? -1 : 1;
  const x = useTransform(progress, [0, 1], [`${String(sign * 60)}vw`, "0vw"]);
  const rotate = useTransform(progress, [0, 0.8, 1], [sign * 8, sign * -1.5, 0]);
  const opacity = useTransform(progress, [0, 0.5], [0, 1]);
  const Tag = inline ? motion.span : motion.div;
  return (
    <Tag style={{ x, rotate, opacity }} className={inline ? "inline-block" : "min-w-0"}>
      {children}
    </Tag>
  );
}

/**
 * Two halves slide in from opposite edges and lock together, with a slight
 * overshoot in rotation as they meet.
 */
export function JoinSides({ left, right, className, inline = false }: JoinSidesProps) {
  // Typed for both wrapper tags so the same ref fits either.
  const ref = useRef<HTMLDivElement & HTMLSpanElement>(null);
  const Wrapper = inline ? "span" : "div";
  const progress = useEntranceProgress(ref, 0.4);

  return (
    <Wrapper ref={ref} className={cn("overflow-x-clip", className)}>
      {progress ? (
        <>
          <Half progress={progress} from="left" inline={inline}>
            {left}
          </Half>
          <Half progress={progress} from="right" inline={inline}>
            {right}
          </Half>
        </>
      ) : (
        <>
          <Wrapper className={inline ? undefined : "min-w-0"}>{left}</Wrapper>
          <Wrapper className={inline ? undefined : "min-w-0"}>{right}</Wrapper>
        </>
      )}
    </Wrapper>
  );
}
